
=== Late Policy

The purpose of assignments, labs, and projects is to give you hands on
experience with the topics from class. The weekly time commitment for this
course is aimed to be 10 hours per week (includes lecture/lab time).

In general, *no late work will be accepted**. The goal of this policy is to
prevent you from falling behind in the material. It is better to submit
partial work than none at all. However, we realize that you may not be able
to complete a deadline for any number of valid reasons. If you know of a
conflict in advance by more than one week, you may arrange (over email) for a
maximum 2 day extension. For example, if you must travel on a potential due
date, have an interview, or an exam that conflicts with the due date, you may
ask for an extension with enough advanced notice.

If you need to miss a lab, you can submit your work 
electronically by midnight on the day the exercises are assigned. Email the 
instructor with a photo of your work. 

Your lowest assignment grade will dropped. Thus, you may also miss an
assignment without penalty for any reason.